### ISSUE TITLE
Class 'Imagick' not found

### ISSUE THREAD

**Issue by mikerodham** [spatie/pdf-to-image#98] opened 2018-04-18 13:37 UTC
I've just taken over some code at work and run in to an issue with Imagick that I can't seem to fix. Currently running 2 versions of this code one for Laravel 4.2 then I've upgraded 90% of this app using Laravel Shift so we're now running 5.6 and this is the only thing I can't fix. It also has  seemed to stop working for the Laravel 4.2 version on a local homestead.

The version called in composer.json is "^1.2"

Pdf.php

```
public function getImageData($pathToImage)
      {
        $imagick = new \Imagick();
 
        $imagick->setResolution($this->resolution, $this->resolution);
 
        $imagick->readImage(sprintf('%s[%s]', $this->pdfFile, $this->page - 1));
 
        $imagick->mergeImageLayers(\Imagick::LAYERMETHOD_FLATTEN);
 
        $imagick->setFormat($this->determineOutputFormat($pathToImage));
 
        return $imagick;
    }
```

Code I'm Debugging:
```
if (pathinfo($attachement_path, PATHINFO_EXTENSION) == 'pdf') {
                $pdf = new Pdf(public_path() . "/". $attachement_path);
                $pdf->setResolution(264);
                $pdf->saveImage(public_path() . "/" . 'attachment_path/' . pathinfo($attachement_path, PATHINFO_FILENAME) . '.jpg');
            }
```

**Comment by freekmurze** [comment] 2018-04-18 20:52
The error makes me think that the [imagick php extension](http://php.net/manual/en/imagick.setup.php) is not installed on your system.

Closing this because this is a configuration problem on your part not caused by this package.

**Closed by freekmurze** 2018-04-18 20:52 UTC

**Comment by mikerodham** [comment] 2018-04-18 21:36
Not saying you're wrong, but according to phpinfo() on the server, it does appear as installed. Will continue to debug see what I can find out.

**Comment by mikerodham** [comment] 2018-04-25 16:43
I setup a new server and it seemed to work fine, definitely worth double checking if imagick is installed.

**Comment by bymayo** [comment] 2018-10-23 08:38
As I'm a bit of a composer amateur, this problem hit me as well! So I found a solution...

I found that Composer (on MacOS) was using the local version of PHP:

`/usr/bin/php`

Not the version of PHP I wanted, which was the one I was running in MAMP. 

In this version of PHP, Imagick wasn't enabled. So you could either edit the `php.ini` for this php version. Or tell your system to use your MAMP version of PHP, not your local MacOS installed version.

Following this - https://gist.github.com/kkirsche/5710272 you link your PHP version to MAMP and voila, it works! So running `which php` in terminal now produces:

`/Applications/MAMP/bin/php/php7.1.3/bin/php`

(Obviously just ensure that Imagick is enabled in `php.ini` in this version also)

**Comment by satyanstpl** [comment] 2021-04-19 07:18
- spatie/pdf-to-image 2.1.0 requires ext-imagick * -> it is missing from your system. Install or enable PHP's imagick extension.
why I am getting same error I have installed imagick i can check in phpinfo();

**Comment by ibraheem9** [comment] 2022-10-10 18:41
I have the same problem and am sure that imagick is installed and works fine in PHP pure code.
does anyone can help me and save time?

**Comment by ibraheem9** [comment] 2022-10-10 18:47
I found the problem is that in wamp you have to edit the PHP.ini file in the same PHP version that you installed the imagick extension on it 
not from thee wamp GUI

**Comment by JayavelSkyraan** [comment] 2023-02-23 13:26
jjk

**Comment by JayavelSkyraan** [comment] 2023-02-23 13:26
> I have the same problem and am sure that imagick is installed and works fine in PHP pure code. does anyone can help me and save time?
nnnn
